import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {parseHTML} from 'linkedom';
import {buildSearch,resultCategories,indexedCoverage,combineLectureResults,filterCategories} from '../public/search.mjs';

test('semantic UI waits, debounces, rejects stale results, and preserves recording controls and site font',async t=>{
 const {window,document}=parseHTML(await readFile(new URL('../public/index.html',import.meta.url),'utf8'));
 const base='https://leccap.engin.umich.edu/leccap/player/r/';
 const records=Array.from({length:4},(_,i)=>({id:String(i),category:'Lecture recordings',title:`Lecture ${i+1} · Synthetic`,section:'0:10–0:40',text:'Synthetic caption: absolute loss is minimized by a median.',url:base+`fixture${i}?start=5`,start:10,end:40,detail:'Leccap captions',concepts:[],lectureDate:`2026-09-0${i+1}`}));
 records.push({...records[0],id:'overlap',start:30,end:60,url:base+'fixture0?start=25'});
 records.push({id:'pdf',category:'Lecture PDFs',title:records[0].title,section:'Page 2',text:'Absolute loss PDF explanation.',url:'https://example.org/lecture-1.pdf#page=2',detail:'PDF',concepts:[]});
 records.push({id:'note',category:'Notes',title:'Note',section:'Loss',text:'Absolute loss uses the median.',url:'https://example.org/note/#loss',detail:''});
 const messages=[];let autoReply=false;
 const reply=message=>globalThis.testWorker.onmessage({data:{type:'results',id:message.id,query:message.query,results:buildSearch(records)(message.query).map(d=>({...d,locations:d.locations.map(l=>({...l,cosine:.724,score:1.124}))}))}});
 Object.assign(globalThis,{window,document,parent:{postMessage(){}},location:{href:'http://localhost/index.html?embedded=1',search:'?embedded=1',origin:'http://localhost'},Worker:class {constructor(){globalThis.testWorker=this;}postMessage(message){if(!message.query)return;messages.push(message);if(autoReply)reply(message);}},fetch:async url=>({ok:true,json:async()=>String(url).includes('config.json')?{courseName:'EECS 245',websiteURL:'https://eecs245.org',categories:resultCategories,footerLinks:[{label:'All notes chapters',url:'https://notes.eecs245.org'},{label:'All past exams',url:'https://exams.eecs245.org'}],queryShorthand:{absolute:'absolute loss'}}:({records,metadata:{recordings:{published:4,available:4,recordings:records.slice(0,4).map(r=>({...r,status:'available'}))}}})})});
 await import('../public/app.js');
 const input=document.querySelector('#search');input.value='absolute loss';
 document.querySelector('#search-form').dispatchEvent(new window.Event('submit',{cancelable:true}));
 assert.equal(messages.length,0);assert.equal(document.querySelector('.card'),null);
 globalThis.testWorker.onmessage({data:{type:'ready'}});
 assert.equal(messages.length,1);assert.equal(document.querySelector('.card'),null);
 reply(messages[0]);autoReply=true;
 const group=()=>document.querySelector('.group[data-category="Lectures"]');
 assert.deepEqual([...document.querySelectorAll('.filter')].map(b=>b.dataset.category),resultCategories);
 assert.equal(document.querySelector('.group').dataset.category,'Lectures');
 assert.equal(group().querySelectorAll('.card').length,3);
 assert.match(group().querySelector('.card-excerpt').textContent,/absolute loss/);
 assert.equal(group().querySelectorAll('.card')[0].querySelectorAll('.locations a').length,2);
 assert.equal(group().querySelector('.locations a').getAttribute('href'),base+'fixture0?start=5');
 assert.equal(group().querySelector('.locations a').textContent,'0:10–1:00');
 assert(group().querySelector('details.passages summary'));
 const recording=group().querySelector('details.recording-moments');
 assert.equal(recording.open,false);
 assert(recording.querySelector('.recording-summary .recording-thumbnail'));
 assert(!recording.querySelector('.recording-summary .locations'));
 assert(recording.querySelector('.recording-content .locations'));
 assert.equal(document.querySelector('.match-similarity'),null);
 recording.open=true;recording.dispatchEvent(new window.Event('toggle'));
 globalThis.testWorker.onmessage({data:{type:'ready'}});
 assert.equal(group().querySelector('details.recording-moments').open,true);
 group().querySelector('.show-more').click();assert.equal(group().querySelectorAll('.card').length,4);
 const filter=document.querySelector('button[data-category="Lectures"]');
 assert(filter.classList.contains('lectures'));
 filter.click();assert.equal(filter.getAttribute('aria-pressed'),'false');
 assert.equal(group(),null);
 assert(document.querySelector('.note-card'));
 filter.click();assert.equal(filter.getAttribute('aria-pressed'),'true');assert(group());
 globalThis.testWorker.onmessage({data:{type:'ready'}});assert(group());
 document.querySelector('[data-sort="chronological"]').click();
 assert.match(group().querySelector('.recording-label').textContent,/Lecture 1/);
 assert.equal(document.querySelector('#recording-coverage'),null);
 assert.match(document.querySelector('#index-coverage').textContent,/Lecture recordings: 1-4/);
 assert([...group().querySelectorAll('a')].every(a=>a.rel==='noreferrer'));
 const footer=document.querySelector('.index-coverage');
 assert.match(footer.querySelector('p').textContent,/• All notes chapters • All past exams$/);
 assert(!footer.querySelector('p').textContent.includes(' · '));
 assert(document.querySelector('.search-explanation').textContent.startsWith('How matches workFirst, all course content is broken up into chunks.'));
 assert.equal(document.querySelector('.search-explanation code').textContent,'all-MiniLM-L6-v2');
 assert.equal(document.querySelector('.search-explanation a').getAttribute('href'),'https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2');
 assert.equal(footer.querySelectorAll('a')[0].getAttribute('href'),'https://notes.eecs245.org');
 assert.equal(footer.querySelectorAll('a')[1].getAttribute('href'),'https://exams.eecs245.org');

 const submit=()=>document.querySelector('#search-form').dispatchEvent(new window.Event('submit',{cancelable:true}));
 t.mock.timers.enable({apis:['setTimeout']});autoReply=false;
 const count=messages.length;
 input.value='linear';input.dispatchEvent(new window.Event('input'));
 t.mock.timers.tick(200);
 input.value='linear regression';input.dispatchEvent(new window.Event('input'));
 t.mock.timers.tick(349);assert.equal(messages.length,count);assert(group());
 t.mock.timers.tick(1);assert.equal(messages.length,count+1);assert(group());
 const outdated=messages.at(-1);
 input.value='projection';input.dispatchEvent(new window.Event('input'));
 reply(outdated);assert(group());assert.match(document.querySelector('#summary').textContent,/absolute loss/);
 submit();assert.equal(messages.length,count+2);assert.equal(messages.at(-1).query,'projection');
 t.mock.timers.tick(400);assert.equal(messages.length,count+2);
 reply(messages.at(-1));assert.equal(group(),null);assert.match(document.querySelector('#summary').textContent,/projection/);
 input.value='MEAN ABSOLUTE ERROR';submit();assert.equal(messages.length,count+2);assert(group());
 input.value='squared loss';input.dispatchEvent(new window.Event('input'));input.value='';input.dispatchEvent(new window.Event('input'));
 t.mock.timers.tick(400);assert.equal(messages.length,count+2);assert(document.querySelector('#results').hidden);
 input.value='absoluet loss';submit();assert(group());assert.match(document.querySelector('.search-correction').textContent,/absolute loss/);
 const fontMessage=(origin,source,fontFamily)=>{const event=new window.Event('message');Object.assign(event,{origin,source,data:{type:'course-search-font',fontFamily}});window.dispatchEvent(event);};
 fontMessage(location.origin,parent,'Palatino, serif');assert.equal(document.documentElement.style.getPropertyValue('--course-font'),'Palatino, serif');
 fontMessage('https://untrusted.example',parent,'bad');fontMessage(location.origin,{},'bad');assert.equal(document.documentElement.style.getPropertyValue('--course-font'),'Palatino, serif');
 fontMessage(location.origin,parent,'system-ui, sans-serif');assert.equal(document.documentElement.style.getPropertyValue('--course-font'),'system-ui, sans-serif');
 globalThis.testWorker.onmessage({data:{type:'error',message:'Model unavailable'}});
 input.value='squared loss';submit();assert.equal(messages.length,count+2);assert.match(document.querySelector('#timing').textContent,/Refresh to try again/);assert(group());
});

test('indexed coverage preserves gaps and distinguishes PDF and caption coverage',()=>{
 const record=(category,title)=>({category,title});
 const rows=[record('Lecture recordings','Lecture 1 · Intro'),record('Lecture recordings','Lecture 3 · Vectors'),record('Lecture PDFs','Lecture 1 · Intro'),record('Lecture PDFs','Lecture 2 · Loss'),record('Lecture PDFs','Lecture 3 · Vectors'),record('Homeworks','Homework 1: Intro'),record('Homeworks','Homework 3: Vectors')];
 assert.match(indexedCoverage(rows),/Lecture recordings: 1, 3 • Lecture PDFs: 1-3/);
 assert.match(indexedCoverage(rows),/Homeworks: 1, 3/);
 rows.push(record('Lecture recordings','Lecture 2 · Loss'));
 assert.match(indexedCoverage(rows),/^Lectures: 1-3/);
});

test('lecture cards combine matched formats without losing links or overriding filters',()=>{
 const document=(category,title,url,score)=>({id:category+url,category,title,url,score,locations:[{url:url+'#hit',text:'Matching passage',score,category}]});
 const recording=document('Lecture recordings','Lecture 2 · Loss','https://example.org/recording',8);
 const pdf=document('Lecture PDFs','Lecture 2 · Loss','https://example.org/lecture.pdf',4);
 const onlyPDF=document('Lecture PDFs','Lecture 3 · Regression','https://example.org/lecture3.pdf',6);
 const note=document('Notes','Note','https://example.org/note',9);
 const input=[pdf,note,recording,onlyPDF],before=JSON.stringify(input);
 const combined=combineLectureResults(input);
 assert.equal(combined.length,3);
 const lecture=combined.find(d=>d.title===recording.title);
 assert.equal(lecture.score,8);assert.equal(lecture.recording,recording);assert.equal(lecture.pdf,pdf);
 assert.deepEqual(lecture.locations.map(l=>l.url),[recording.locations[0].url,pdf.locations[0].url]);
 const filtered=combineLectureResults(filterCategories(input,new Set(['Lecture PDFs'])));
 assert.equal(filtered.length,2);assert(filtered.every(d=>d.recording===null&&d.pdf));
 assert.equal(combineLectureResults(filterCategories(input,new Set(['Lectures']))).length,2);
 assert.equal(filterCategories(input,new Set(['Lectures'])).length,3);
 assert.equal(JSON.stringify(input),before);
});
